### ISSUE TITLE
2021.2 Compatibility

### ISSUE THREAD

**Issue by anstarovoyt** [olance/intellij-prisma#11]
Hi! First of all, thank you for the great plugin! 

Version 2021.2 of the IDE was released several weeks ago and the plugin isn't compatible with it. Could you please update the since-until range?

**Comment by anstarovoyt** [comment]
I've created a PR https://github.com/olance/intellij-prisma/pull/12

Also, I've built the plugin, see the attachment 
[intellij-prisma-1.0.3.212.zip](https://github.com/olance/intellij-prisma/files/7047049/intellij-prisma-1.0.3.212.zip)

**Comment by olance** [comment]
Many thanks for the effort of fixing and building the plugin! 👌 

I've just pushed changes to the Gradle build file and the `plugin.xml` one, so that there's no `until-build` range defined anymore, which means the plugin should stop being considered incompatible with each and every new IDE version! 🤞
