### ISSUE TITLE
There are errors here

### ISSUE THREAD

**Issue by aikin-vip** [olance/intellij-prisma#13]
![image](https://user-images.githubusercontent.com/64122272/143002950-1fbfa1ab-6ce6-4ed5-a0a6-15023eb2bcc0.png)

**Comment by aikin-vip** [comment]
it seems  #3

**Comment by olance** [comment]
@aikin-vip thanks for the report!

Note for myself:
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#model-fields

Will fix ASAP, sorry about this

**Comment by NGRichter** [comment]
Hi,
I also came across this or a similar error, see the picture. 
It does not really bother me as Prisma still runs but when I want to git commit/push, the IDE always keeps telling me "Checks failed: 1 error" because of it and I cannot disable the check. 
![schema prisma](https://user-images.githubusercontent.com/22129925/146951028-2f5aef4b-a581-4529-b091-ba95fa08f460.png)

**Comment by dburenok-copperleaf** [comment]
Having a similar issue on Webstorm.
![image](https://user-images.githubusercontent.com/97476720/171517666-4b8fc222-8391-438c-868b-cd781a424588.png)
`Error:(20, 1) <model block statement>, PrismaTokenType.DOUBLE_COMMENT, PrismaTokenType.ENTITY_NAME, PrismaTokenType.EOL, PrismaTokenType.TRIPLE_COMMENT or PrismaTokenType.} expected, got 'some_prop_name'`
