### ISSUE TITLE
Unsupported @updatedAt attribute 

### ISSUE THREAD

**Issue by MarcioBarrientos** [olance/intellij-prisma#3]
The plugin treat @updatedAt attribute as an error and stop inspecting the code after.
[https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#updatedat](url)

This is the error I get:
`<model block statement>, PrismaTokenType.DOUBLE_COMMENT, PrismaTokenType.ENTITY_NAME, PrismaTokenType.EOL, PrismaTokenType.MODEL_FIELD_ATTRIBUTE_NAME, PrismaTokenType.TRIPLE_COMMENT or PrismaTokenType.} expected, got 'updatedAt'`

DateTime and String not being formatted because it stops in the error
![Captura de Pantalla 2021-03-03 a la(s) 10 54 56](https://user-images.githubusercontent.com/4836851/109842070-4e016500-7c0f-11eb-85e7-0364bd921230.png)

**Comment by justinhandley** [comment]
I also am running into this.  Any word on where it stands?

**Comment by olance** [comment]
Yes, this was not documented in the [Prisma schema reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference) when I first implemented this plugin.

There are other attributes that made them to the spec since then as well, such as `@ignore`/`@@ignore` that appeared last month.

I will update the plugin's grammar to take them into account – I wish there was a way to subscribe to changes of this reference 😓

**Comment by olance** [comment]
Update 1.0.3 of the plugin has been pushed to Jetbrains Plugins and is awaiting approval!
